### PR TITLE
Added support for PDO & fixed PHP 8 errors

### LINKED ISSUE #273: Warning: Declaration of debugErrorHandler::error should be compatible with errorHandler::error in /mybb/merge/resources/class_error.php on line 0
Situation:

1. mybb 1.8.27 setup new, nothing done except setup
2. merge 1.8.23 
3. Launcnh : big warning
4. PHP Version 7.3.29-1~deb10u1 / nginx

I make the pull request in some minute (or tomorrow).
Capture d’écran du 2021-07-12 18-53-45

### LINKED ISSUE #276: New PDO based DB drivers for MySQL and PostgreSQL as of 1.8.27
New PDO based DB drivers for MySQL and PostgreSQL have been introduced in https://github.com/mybb/mybb/pull/4193.

### PR DESCRIPTION
**Pull request by bram1000**
There will still be a lot of warnings in PHP 8 but at least the merge system will be functional. The thing I worry about the most is the following line of code:
`function error($type, $message, $file=null, $line=0, $allow_output=false)`

I set the default to false because the merge system has so many warnings that it becomes unusable because it obscures the view, temporary fix until the merge system has been rewritten?

### CODE REVIEW

**Comment by euantorano** [comment]
Wow, great work. I'll have a look through this today and post any feedback.

**Comment by bram1000** [comment]
@euantorano Any updates about this pull request?

File: index.php [hunk 1]
```diff
@@ -141,6 +141,9 @@
 {
 	require_once MYBB_ROOT."inc/db_base.php";
 }
+if($config['database']['type'] == "mysql_pdo") {
+	require_once MYBB_ROOT."inc/AbstractPdoDbDriver.php";
+}
```
Comment (yuliu) [inline index.php]: In my opinion, `inc/db_base.php` and `inc/AbstractPdoDbDriver.php` can be included safely without any _if_, just as MyBB does in

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/init.php#L124-L126

File: index.php [hunk 2]
```diff
@@ -153,6 +156,9 @@
 	case "mysqli":
 		$db = new DB_MySQLi;
 		break;
+	case "mysql_pdo":
+		$db = new MysqlPdoDbDriver;
+		break;
```
Comment (yuliu) [inline index.php]: There's another `PostgresPdoDbDriver` class, you may also want to add it. By the way, it might be better to append brackets to the classnames here as done in MyBB's `inc/init.php`

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/init.php#L130-L149

File: index.php [hunk 3]
```diff
@@ -126,7 +126,7 @@
 	$mybb->settings['uploadspath'] = MYBB_ROOT.$mybb->settings['uploadspath'];
 }
 
-require_once MYBB_ROOT."inc/class_xml.php";
+require_once MYBB_ROOT."inc/class_xmlparser.php";
```
Comment (yuliu) [inline index.php]: I guess we may discard this line and use [`create_xml_parser()`](https://github.com/mybb/mybb/blob/mybb_1829/inc/functions.php#L9417), already provided by MyBB a few versions ago, whenever we want a XML parser.

File: index.php [hunk 4]
```diff
@@ -595,11 +601,11 @@
 	$checks['version_check_status'] = '<span class="pass">'.$lang->requirementspage_uptodate.'</span>';
 
 	// Check for a new version of the Merge System!
-	require_once MYBB_ROOT."inc/class_xml.php";
+	require_once MYBB_ROOT."inc/class_xmlparser.php";
```
Comment (yuliu) [inline index.php]: Same here.

File: index.php [hunk 5]
```diff
@@ -595,11 +601,11 @@
...
 	$contents = merge_fetch_remote_file("http://www.mybb.com/merge_version_check.php");
 	if($contents)
 	{
-		$parser = new XMLParser($contents);
+		$parser = new MyBBXMLParser($contents);
```
Comment (yuliu) [inline index.php]: We may call [`create_xml_parser($contents)`](https://github.com/mybb/mybb/blob/mybb_1829/inc/functions.php#L9417) to get a XML parser for `$contents`.

**Review by yuliu — CHANGES_REQUESTED** [review]
I've left some opinions on this PR. Hope we could fix them, @nixpc.

File: resources/class_error.php [hunk 6]
```diff
@@ -31,7 +31,7 @@ function __construct()
 	 * @param integer $line The error line
 	 * @return boolean True if parsing was a success, otherwise assume a error
 	 */
-	function error($type, $message, $file=null, $line=0)
+	function error($type, $message, $file=null, $line=0, $allow_output=false)
```
Comment (yuliu) [inline resources/class_error.php]: Here the default value for `$allow_output` might be better to set to `true`, and the PHPDoc needs to be updated.

**Comment by yuliu** [comment]
OK, I'll try to update your PR.

**Review by yuliu — APPROVED** [review]

**Comment by yuliu** [comment]
> There will still be a lot of warnings in PHP 8 but at least the merge system will be functional. The thing I worry about the most is the following line of code: `function error($type, $message, $file=null, $line=0, $allow_output=false)`
> 
> I set the default to false because the merge system has so many warnings that it becomes unusable because it obscures the view, temporary fix until the merge system has been rewritten?

We're seeing so many PHP warnings when using the merge system on PHP 8 because these warnings are waiting to be fixed and we want it to show all the warnings (#255). And I changed the default value of `$allow_output` to `true`, which is the default behavior of MyBB's error reporting functionality, because we want the merge system to output as many errors/warnings as possible so that we could help users with their imports.

**Review by yuliu — CHANGES_REQUESTED** [review]
There's one more thing we need to do. The new PDO methods should be supported for the function [`print_database_details_table()`](https://github.com/mybb/merge-system/blob/merge_1823/resources/output.php#L416) in `/resources/output.php`.

I'll push some more commits later.

**Comment by yuliu** [comment]
There's one more place to change but I'll leave it in another PR to avoid conflicts.
https://github.com/mybb/merge-system/blob/21175e369ef28b80e991dabffc8850efb5017079/resources/functions.php#L319

**Review by yuliu — APPROVED** [review]
