### PR TITLE
Fix #243 `parentlist` is not properly set for root categories in MyBB forums module

### LINKED ISSUE #243: MyBB's forums module: `parentlist` is not properly set for root categories (type c forum)
## Issue:
The `parentlist` field of a merged type `c` (category) forum is the old value from the old database.
One potential bug I can find currently due to this issue for the final merged forum is about forum password:
- If the old value from an imported forum, called forum X, is an ID of an existing forum, let's call it forum A,
- and if forum A has a password for users to enter to view it,

then, no matter or not X has a password, it'll need a password for entering X.

## Cause:
Since MyBB Merge Module doesn't have a categories module, all forums are merged by the forums module. In the MyBB's forums module, all data fields from the old database will be imported as what they are except that each forum's parent ID (`pid`) will be set to `0` for the `cleanup()` to work. However, none of them will take care of imported root categories.

There are two `cleanup()`s:
1. re-create each forum's parent ID and parent list (`parentlist`) from MyBB's forums module;
2. create a new category and re-arrange forums without a parent as child forums of it from base forums module.

In a proper MyBB installation, each type `f` forum is sorted as a child forum of a type `c` category forum, so in a MyBB merge, the second `cleanup()` will actually done nothing. While the first `cleanup()` will just exclude such root categories from being processed (`import_pid` will be `0` for them) https://github.com/mybb/merge-system/blob/bd7fd6b87d64ed568d6d28867e8c61e2ab38c607/boards/mybb/forums.php#L103
Anyway, the first `cleanup()` that make use of `make_mybb_parent_list()` will probably fail when processing a root category.

## Solution:
Set `parentlist` field's value of a root category to its new `fid` after it's imported.

### PR DESCRIPTION
**Pull request by yuliu**
Resolves #243.

Deleted following code in MyBB forums module which is not really needed I suppose:
```
		// This value NEEDS to be here for the cleanup() to work
		$insert_data['pid'] = 0;
```

### CODE REVIEW

File: boards/mybb/forums.php [hunk 1]
```diff
@@ -96,11 +93,19 @@ function cleanup()
 	{
 		global $db;
 
+		// Imported root Category forums (type 'c' forums whose parent is "None").
```
Comment (JordanMussi) [inline boards/mybb/forums.php]:
```suggestion
		// Cleanup root category forums (type 'c' forums whose parent is "None").
```

File: boards/mybb/forums.php [hunk 2]
```diff
@@ -96,11 +93,19 @@ function cleanup()
...
+		$query = $db->simple_select("forums", "fid", "import_fid != '0' AND import_pid = '0'");
+		while($forum = $db->fetch_array($query))
+		{
+			$db->update_query("forums", array('parentlist' => $forum['fid']), "fid='{$forum['fid']}'", 1);
+		}
+
+		// Ohter imported forums.
```
Comment (JordanMussi) [inline boards/mybb/forums.php]:
```suggestion
		// Cleanup other imported forums
```

**Review by JordanMussi — APPROVED** [review]
